---
title: "hw5"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Step 0: Please install and load the following packages
library(dplyr)
library(Seurat)
library(patchwork)

```

```{r}
#Step 1: Load the TSV file
data = read.table(file = 'GSM3036909.tsv', sep = '\t', header = TRUE)
```

```{r}
rownames(data) = data$Genes
```


```{r}
data$Genes = NULL
```


```{r}
#Step 2: Create a Seurat object. Call the object pdac1. You set the project argument in the CreateSeuratObject the same. Here we will also request the same criteria as mentioned in the workflow: min.cells=3 and min.features=200.
pdac1 =  CreateSeuratObject(counts = data, project = "pdac1", min.cells = 3, min.features = 200)

```

```{r}
pdac1
```

```{r}
#Step 3: Label the Mitochondrial genes. We don’t want to use cells that have too many mitochondrial genes, so we create a new column to help us summarize how many mitochondrial genes were identified in the different cells.
pdac1[["percent.mt"]] <- PercentageFeatureSet(object = pdac1, pattern = "^MT-")

```

```{r}
#Step 4: Visualize the distribution. Use the VlnPlot function to view the number of counts, number of features, and the percent mitochondrial genes.
VlnPlot(object = pdac1, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

```

```{r}
#Step 5: Filter data. Only keep the cells that have greater than 200 and less than 2500 unique features and the percent mitochondrial genes is less than 5.
pdac1 <- subset(x = pdac1, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)

```

```{r}
#Step 6: Normalize data. Taking the log of the data, makes the data more normal distributed. Normalize data using the LogNormaliza method with a scale factor of 10,000
pdac1 <- NormalizeData(object = pdac1, normalization.method = "LogNormalize", scale.factor = 10000)

```

```{r}
#Step 6: Calculate gene variation.Find the 2000 most variable genes using the FindVariableFeatures command using the vst method.
pdac1 <- FindVariableFeatures(object = pdac1, selection.method = "vst", nfeatures = 2000)
```

```{r}
# Step 7: Scale data. Scaling the data normalizes the standard deviation and centers the data. This is an important step before performing PCA.
all.genes <- rownames(x = pdac1)
pdac1 <- ScaleData(object = pdac1, features = all.genes)


```

```{r}
# Step 8: PCA Run PCA
pdac1 <- RunPCA(object = pdac1, features = VariableFeatures(object = pdac1))

```

```{r}
# Step 9: Visualize data using VizDimLoadings and DimPlot functions. Can you tell from the PCA analyis, the number of cell types that are present?
VizDimLoadings(object = pdac1, dims = 1:2, reduction = "pca")
```

From the PCA analysis you cannot see the number cell types that are present. 

```{r}
# Step 9
DimPlot(object = pdac1, reduction = "pca")
```

```{r}
#Step 10: PCA heatmaps. Another way to visualize the variation explained by the PC is creating heatmaps. Create heatmaps of the first 10 dimensions and include 200 cells.
DimHeatmap(object = pdac1, dims = 1:10, cells = 200, balanced = TRUE)


```

```{r}
#Step 11: Dimensionality. To make this more quantitative, let’s see when does the variation reach the lowest amount of variation explained. Use the JackStraw method with 100 replicates and score the first 20 dimensions.Plot the results for the first 20 dimensions. Use the elbow plot

pdac1 = JackStraw(object = pdac1, num.replicate = 100) 
pdac1 = ScoreJackStraw(object = pdac1, dims = 1:20)
ElbowPlot(object = pdac1)
```

```{r}
# Step 12: Clustering. Now we will group together the cells based on where they are located in the different dimensions. Use the FindNeighbors function using the first 9 dimensions. And then identify the clusters usng the FindClusters function.
pdac1 <- FindNeighbors(object = pdac1, dims = 1:10)
pdac1 <- FindClusters(object = pdac1, resolution = 0.5)
```

```{r}
# Step 13: Perform a UMAP analysis using the first 9 dimensions using RunUMAP and then visualize it using DimPlot. How many clusters do you get? How many possible mistakes do you see?
pdac1 <- RunUMAP(object = pdac1, dims = 1:10)
DimPlot(object = pdac1, reduction = "umap")

```

I have four clusters with 5 possible mistakes. 
```{r}
# Step 14: Identify the markers that compare each cluster agains all. Report only positively markers. Use the FindAllMarkers for this.
pdac1.markers <- FindAllMarkers(object = pdac1, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
pdac1.markers %>%
    group_by(cluster) %>%
    slice_max(n = 2, order_by = avg_log2FC)
```

```{r}
# Step 15: Create a violin plot using one feature from each cluster.
VlnPlot(object = pdac1, features = c("SPP1", "RGS1","S100A9", "MGP"))

```

```{r}
# Step 16: Create a feature plot using the same features as before.
FeaturePlot(object = pdac1, features = c("SPP1", "RGS1","S100A9", "MGP"))
```


