---
title: "Untitled"
author: "Chandana"
date: "5/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Referred [GSEA by NYU Gencore][https://learn.gencore.bio.nyu.edu/rna-seq-analysis/over-representation-analysis/] for Over representation analysis

```{r eval=F}
#BiocManager::install("clusterProfiler")
#BiocManager::install("enrichplot")
#BiocManager::install("pathview")
library(clusterProfiler)
library(enrichplot)
library(pathview)
library(wordcloud)
```


########################################3

```{r}
cl1 = clusters_df$clusters==1
cl1 = clusters_df[cl1,]
```

```{r}
cl2 = clusters_df$clusters==2
cl2 = clusters_df[cl2,]

cl3 = clusters_df$clusters==3
cl3 = clusters_df[cl3,]

cl4 = clusters_df$clusters==4
cl4 = clusters_df[cl4,]

cl5 = clusters_df$clusters==5
cl5 = clusters_df[cl5,]

cl6 = clusters_df$clusters==6
cl6 = clusters_df[cl6,]

cl7 = clusters_df$clusters==7
cl7 = clusters_df[cl7,]

cl8 = clusters_df$clusters==8
cl1 = clusters_df[cl1,]
```
#############################################################

```{r}
gene_list = diff_genes$`NCBI gene (formerly Entrezgene) ID`
gene_list = sort(gene_list, decreasing = T)
gene_list<-na.omit(gene_list)

```

## GSEA Analysis
```{r}
organism = "org.Hs.eg.db"
library(organism, character.only = TRUE)

gse <- gseGO(geneList=gene_list, 
             ont ="GO", 
             keyType = "ENTREZID", 
             nPerm = 10000, 
             #minGSSize = 3, 
             #maxGSSize = 800, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = organism, 
             pAdjustMethod = "none")
```


```{r}
T1_list = top.table3$T_1
names(T1_list) = rownames(top.table3)

T1_genelist = na.omit(T1_list)
T1_genelist = sort(T1_genelist, decreasing = TRUE)

sig_genes = subset(top.table3, adj.P.Val<0.05)

genes_T1 = sig_genes$T_1
names(genes_T1) = rownames(sig_genes)
genes_T1 <- na.omit(genes_T1)

# filter on min log2fold change (log2FoldChange > 2)
genes_T1 <- names(genes_T1)[abs(genes_T1) > 2]

genes_T1
```

```{r}
genes_list.T1 = BMresults[BMresults$`Gene stable ID version` %in% genes_T1, ]
#dim(genes_list.T1)
genes_list.T1 = distinct(genes_list.T1, `NCBI gene (formerly Entrezgene) ID`)
#genes_list.T1 = as.data.frame(genes_list.T1)
#dim(genes_list.T1)
genes_list.T1 = genes_list.T1$`NCBI gene (formerly Entrezgene) ID`
class(genes_list.T1)
write.table(genes_list.T1, "genes.T1", sep=" ", row.names = F, col.names = F)
```

```{r}

gene_list = BMresults[BMresults$`Gene stable ID version` %in% rows, ]
gene_list = distinct(gene_list, `NCBI gene (formerly Entrezgene) ID`)
gene_list = gene_list$`NCBI gene (formerly Entrezgene) ID`
head(gene_list)
```

## Barplot

```{r}
# creating GOenrich onject for time T1
go_enrich <- enrichGO(gene = genes_list.T1,
                      universe = names(gene_list),
                      OrgDb = organism, 
                      keyType = 'ENTREZID',
                      readable = T,
                      ont = "BP",
                      pvalueCutoff = 0.05, 
                      qvalueCutoff = 0.10)
```




```{r}
barplot(go_enrich, 
        drop = TRUE, 
        showCategory = 10, 
        title = "GO Biological Pathways",
        font.size = 8)
```



## Upset plot

```{r}
#jpeg("upset1.jpg")
upsetplot(go_enrich)
#dev.off()
```
## Wordcloud

```{r eval=F}
#jpeg("worcloud.jpg")
wcdf<-read.table(text=go_enrich$GeneRatio, sep = "/")[1]
wcdf$term<-go_enrich[,2]
wordcloud(words = wcdf$term, freq = wcdf$V1, scale=(c(4, .1)), colors=brewer.pal(8, "Dark2"), max.words = 50)
#dev.off()
```

## cnet plot

```{r}
BiocManager::install("ggnewscale")
library(ggnewscale)
# categorySize can be either 'pvalue' or 'geneNum'
cnetplot(go_enrich, categorySize="pvalue", foldChange=gene_list)
```


```{r}
# for T1

T2_list = top.table3$T_2
names(T2_list) = rownames(top.table3)

T2_genelist = na.omit(T2_list)
T2_genelist = sort(T2_genelist, decreasing = TRUE)

#sig_genes = subset(top.table3, adj.P.Val<0.05)

genes_T2 = sig_genes$T_2
names(genes_T2) = rownames(sig_genes)
genes_T2 <- na.omit(genes_T2)

# filter on min log2fold change (log2FoldChange > 2)
genes_T2 <- names(genes_T2)[abs(genes_T2) > 2]

genes_list.T2 = BMresults[BMresults$`Gene stable ID version` %in% genes_T2, ]
genes_list.T2 = distinct(genes_list.T2, `NCBI gene (formerly Entrezgene) ID`)
genes_list.T2 = genes_list.T2$`NCBI gene (formerly Entrezgene) ID`
write.table(genes_list.T2, "genes.T2", sep=" ", row.names = F, col.names = F)

# creating GOenrich object for time T2
go_enrich2 <- enrichGO(gene = genes_list.T2,
                      universe = names(gene_list),
                      OrgDb = organism, 
                      keyType = 'ENTREZID',
                      readable = T,
                      ont = "BP",
                      pvalueCutoff = 0.05, 
                      qvalueCutoff = 0.10)

#jpeg("wordcloud2.jpg")
wcdf2<-read.table(text=go_enrich2$GeneRatio, sep = "/")[1]
wcdf2$term<-go_enrich2[,2]
wordcloud(words = wcdf2$term, freq = wcdf2$V1, scale=(c(4, .1)), colors=brewer.pal(8, "Dark2"), max.words = 50)
#dev.off()
```

```{r}
#jpeg("upset2.jpg")
upsetplot(go_enrich2)
#dev.off()
```

```{r}
barplot(go_enrich2, 
        drop = TRUE, 
        showCategory = 10, 
        title = "GO Biological Pathways",
        font.size = 8)
```




```{r}
# for time T3
T3_list = top.table3$T_3
names(T3_list) = rownames(top.table3)

T3_genelist = na.omit(T3_list)
T3_genelist = sort(T3_genelist, decreasing = TRUE)

#sig_genes = subset(top.table3, adj.P.Val<0.05)

genes_T3 = sig_genes$T_3
names(genes_T3) = rownames(sig_genes)
genes_T3 <- na.omit(genes_T3)

# filter on min log2fold change (log2FoldChange > 2)
genes_T3 <- names(genes_T3)[abs(genes_T3) > 2]

genes_list.T3 = BMresults[BMresults$`Gene stable ID version` %in% genes_T3, ]
genes_list.T3 = distinct(genes_list.T3, `NCBI gene (formerly Entrezgene) ID`)
genes_list.T3 = genes_list.T3$`NCBI gene (formerly Entrezgene) ID`
write.table(genes_list.T3, "genes.T3", sep=" ", row.names = F, col.names = F)


go_enrich3 <- enrichGO(gene = genes_list.T3,
                      universe = names(gene_list),
                      OrgDb = organism, 
                      keyType = 'ENTREZID',
                      readable = T,
                      ont = "BP",
                      pvalueCutoff = 0.05, 
                      qvalueCutoff = 0.10)

#jpeg("wordcloud3.jpg")
wcdf3<-read.table(text=go_enrich3$GeneRatio, sep = "/")[1]
wcdf3$term<-go_enrich3[,2]
wordcloud(words = wcdf3$term, freq = wcdf3$V1, scale=(c(4, .1)), colors=brewer.pal(8, "Dark2"), max.words = 50)
#dev.off()
```

```{r}
#jpeg("upset3.jpg")
upsetplot(go_enrich3)
#dev.off()
```


```{r}
barplot(go_enrich3, 
        drop = TRUE, 
        showCategory = 10, 
        title = "GO Biological Pathways",
        font.size = 8)
```

